---
kind: Template
apiVersion: v1
metadata:
  name: bespin

parameters:
- name: BESPIN_API_VERSION
  displayName: bespin-api-version
  description: Repository tag to deploy
  required: true
  value: master

- name: BESPIN_API_REPO_URL
  displayName: bespin-api-repo-url
  description: Respository url
  required: true
  value: https://github.com/Duke-GCB/bespin-api

- name: BESPIN_API_URL
  displayName: bespin-api-url
  description: Website url
  required: true
  value: https://bespin.genome.duke.edu/api

- name: BESPIN_API_SECRET_KEY
  displayName: bespin-api-secret-key
  generate: expression
  from: "[a-zA-Z0-9]{50}"

- name: BESPIN_API_ALLOWED_HOST
  displayName: bespin-api-allowed-host
  description: Host that can access the API
  value: "*"

- name: BESPIN_API_MAILER_TOKEN
  displayName: bespin-api-mailer-token
  description: Token to use with bespin api
  value: ''

- name: BESPIN_API_SERVER_NAME
  displayName: bespin-api-mailer-token
  description: Token to use with bespin api
  required: true
  value: 'bespin.genome.duke.edu'

- name: BESPIN_API_GROUP_MANAGER_ACCOUNT_ID
  displayName: bespin-api-group-manager-account-id
  description: Account ID for use with group manager
  value: ''

- name: BESPIN_API_GROUP_MANAGER_PASSWORD
  displayName: bespin-api-group-manager-password
  description: Password for use with group manager
  value: ''

- name: BESPIN_API_GROUP_MANAGER_REQUIRED_GROUP
  displayName: bespin-api-group-manager-required-group
  description: Required group to use bespin-api
  value: ''

- name: BESPIN_UI_VERSION
  displayName: bespin-ui-version
  description: Repository tag to deploy
  required: true
  value: master

- name: BESPIN_UI_REPO_URL
  displayName: bespin-ui-repo-url
  description: Respository url
  required: true
  value: https://github.com/Duke-GCB/bespin-ui

objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: bespin-api
  data:
    build.version: "${BESPIN_API_VERSION}"
    build.repo_url: "${BESPIN_API_REPO_URL}"
    url: "${BESPIN_API_URL}"
    allowed_host: "${BESPIN_API_ALLOWED_HOST}"
    server_name: "${BESPIN_API_SERVER_NAME}"
    group_manager_account_id: "${BESPIN_API_GROUP_MANAGER_ACCOUNT_ID}"
    group_manager_required_group: "${BESPIN_API_GROUP_MANAGER_REQUIRED_GROUP}"

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: bespin-ui
  data:
    build.version: "${BESPIN_UI_VERSION}"
    build.repo_url: "${BESPIN_UI_REPO_URL}"

- kind: Secret
  apiVersion: v1
  metadata:
    name: bespin-api
  stringData:
    secret_key: "${BESPIN_API_SECRET_KEY}"
    group_manager_password: "${BESPIN_API_GROUP_MANAGER_PASSWORD}"
    mailer_token: "${BESPIN_API_MAILER_TOKEN}"

