kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bespin-service-account-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list"]
