kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bespin-service-account-binding
roleRef:
  kind: Role
  name: bespin-service-account-role
subjects:
  - kind: ServiceAccount
    name: bespin-service-account
